# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Morning Artifice
description: > # this means to ignore newlines until "baseurl:"
  The wonderful world of cyberspace.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
host: localhost

# theme: minima
# End

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SITECHANGELOG.md
# End

# Github metadata settings
repository: prokhorvlg/morning-artifice
# End

#logo: /assets/img/logo/MvvmCross-avatar.png

# Date format settings
date_format: "%b %-d, %Y"
# End

# Site permalink settings
permalink: pretty
# End

# Site menu settings
#menu:
#  - title: "Updates"
#    url: "/updates"
#  - title: "Codex"
#    url: "/geography"
# End

sass:
    style: compressed
    sass_dir: assets/css/_sass